apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deploy
  labels:
    type: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      name: app-server-tmpl
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: leo1999806/app-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
